worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    upstream backend_servers {
        server ${MOVIES_SERVICE_URL} weight=${MOVIES_WEIGHT} ${MOVIES_DOWN};
        server ${MONOLITH_URL} weight=${MONOLITH_WEIGTH} ${MONOLITH_DOWN};
    }

    server {
        listen 8000;
        server_name _;

        location /api/users {
            proxy_pass http://${MONOLITH_URL};
        }

        location /health {
            access_log off;
            add_header 'Content-Type' 'application/json';
            return 200 '{"status": true}';
        }

        location /api/movies {
            proxy_pass http://backend_servers;
        }
    }
}
